version: '3.8'

services:
  szl-api:
    container_name: szl-api
    image: "szl-api:latest"  # or "ghcr.io/sz-laeuft/laufevent:latest"
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080  
    restart: always 
