version: "3.9"
services:
  api:
    container_name: laufevent-api
    build: .
    ports:
      - "44320:443"
      - "5021:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword123!
    volumes:
      - ~/.aspnet/https:/https:ro
