services:
  szl-api:
    container_name: szl-api
    image: "ghcr.io/sz-laeuft/laufevent:latest"
    ports:
      - "44320:443"
      - "5021:80"
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=htl
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
