name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/sz-laeuft/laufevent
          docker build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/sz-laeuft/laufevent
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
